# Generated by Django 4.2.5 on 2023-09-12 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0005_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="author",
            options={"default_related_name": "authors"},
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
